const express = require("express");
const adminController = require("../controllers/admin.controller");
const { authenticate, requireAdmin } = require("../middlewares/auth");
const { upload } = require("../middlewares/upload");

const router = express.Router();
router.use(authenticate, requireAdmin);

router.get("/stats", adminController.getDashboardStats);
router.get("/candidates", adminController.getAllCandidates);
router.post("/candidates", upload.single("photo"), adminController.createCandidate);
router.patch("/candidates/:id/approve", adminController.approveCandidate);
router.patch("/candidates/:id/reject", adminController.rejectCandidate);
router.patch("/candidates/:id/votes", adminController.adjustCandidateVotes);
router.patch("/candidates/:id/points", adminController.adjustCandidatePoints);
router.patch("/candidates/:id", upload.single("photo"), adminController.updateCandidate);
router.delete("/candidates/:id", adminController.deleteCandidate);
router.get("/payments", adminController.getAllPayments);
router.post("/payments/reconcile", adminController.reconcilePayments);
router.post("/payments/:id/refund", adminController.refundPayment);
router.get("/users", adminController.getAllUsers);
router.delete("/users/:id", adminController.deleteUser);
router.patch("/users/:id", adminController.updateUser);
router.delete("/votes/:id", adminController.deleteVote);
router.post("/votes/reset", adminController.resetVotes);
router.get("/points/status", adminController.getPointsStatus);
router.post("/points/award", adminController.awardPoints);
router.get("/points/config", adminController.getPointsConfig);
router.put("/points/config", adminController.setPointsConfig);
router.get("/double-votes", adminController.getDoubleVotes);
router.put("/double-votes", adminController.setDoubleVotes);
router.get("/social-links", adminController.getSocialLinks);
router.put("/social-links", adminController.updateSocialLinks);
router.get("/contests", adminController.getContests);
router.post("/contest", adminController.createContest);
router.patch("/contest/:id", adminController.updateContest);
router.patch("/contest/:id/close", adminController.closeVotes);
router.patch("/contest/:id/open", adminController.openVotes);

module.exports = router;
